### PR TITLE
Leverage Moshi 1.4's select() API for better performance

### PR DESCRIPTION
**Pull request by ZacSweers**
This introduces usage of Moshi's new select() APIs when retrieving the name.

Now the generated code looks like this:

```java
package test;

import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.JsonReader;
import com.squareup.moshi.JsonWriter;
import com.squareup.moshi.Moshi;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.reflect.Type;

final class AutoValue_Foo<V> extends $AutoValue_Foo<V> {
  AutoValue_Foo(V item, String name) {
    super(item, name);
  }

  public static final class MoshiJsonAdapter<V> extends JsonAdapter<Foo<V>> {
    private static final String[] NAMES = new String[] {"item","name"};
    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);
    private final JsonAdapter<V> itemAdapter;
    private final JsonAdapter<String> nameAdapter;
    public MoshiJsonAdapter(Moshi moshi, Type[] types) {
      this.itemAdapter = moshi.adapter(types[0]);
      this.nameAdapter = moshi.adapter(String.class);
    }
    @Override
    public Foo<V> fromJson(JsonReader reader) throws IOException {
      reader.beginObject();
      V item = null;
      String name = null;
      while (reader.hasNext()) {
        int index = reader.selectName(OPTIONS);
        String name_;
        if (index != -1) {
          name_ = NAMES[index];
        } else {
          reader.nextName();
          reader.skipValue();
          continue;
        }
        if (reader.peek() == JsonReader.Token.NULL) {
          reader.skipValue();
          continue;
        }
        switch (name_) {
          case "item": {
            item = itemAdapter.fromJson(reader);
            break;
          }
          case "name": {
            name = nameAdapter.fromJson(reader);
            break;
          }
          default: {
            reader.skipValue();
          }
        }
      }
      reader.endObject();
      return new AutoValue_Foo(item, name);
    }
    @Override
    public void toJson(JsonWriter writer, Foo<V> value) throws IOException {
      writer.beginObject();
      writer.name("item");
      itemAdapter.toJson(writer, value.item());
      writer.name("name");
      nameAdapter.toJson(writer, value.name());
      writer.endObject();
    }
  }
}
```

### CODE REVIEW

**Comment by ZacSweers** [comment]
Two bits for discussion from this:

- Is this enough? It still has to do the comparison in the switch statement below. Wondering if we should also be keeping track of the adapter and just directly returning it (e.g. keeping a mapping of names to adapters). CC @swankjesse if you have any insight :)

- Testing this repo is extremely hard due to whatever causes this bug - https://github.com/google/auto/issues/342. I can't even run checkstyle :|

**Comment by ZacSweers** [comment]
@rharter for the failing method checkstyle, can I just bump the limit? Not sure how to make it smaller

**Review by serj-lotutovici — APPROVED** [review]
A name to adapter mapping would certainly reduce the generated methods in size. And as far a I remember a `Map` is as efficient as switch, especial for larger sets. So 👍 from my side.

**Comment by swankjesse** [comment]
If you’re generating the code anyway your switch could be on the index rather than the string.

```
      while (reader.hasNext()) {
        switch (reader.selectName(OPTIONS)) {
          case 0: {
            item = itemAdapter.fromJson(reader);
            break;
          }
          case 1: {
            name = nameAdapter.fromJson(reader);
            break;
          }
          case -1: {
            reader.nextName();
            reader.skipValue();
            break;
          }
        }
      }
```

Also, it’d probably be simpler to make null handling the delegate adapter’s job.

**Comment by ZacSweers** [comment]
Good catch on the int switching, done in 974f49c.

I left the null check for now pending what @rharter thinks. ~I understand why it's there I think. For custom types it's right, but for the built-ins then it requires custom ones for all of those too. Maybe makes sense as a compiler arg?~ Nevermind, moshi's built-ins [are already nullsafe](https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java#L39-L48)

**Comment by ZacSweers** [comment]
Talked with @swankjesse separately. Since moshi already makes the built-ins nullsafe, I agree it should be best left to the adapters. If we remove that peek line, we can remove the entire `index` variable and just inline the `selectName()` call directly to the switch. Will push a commit with that, can revert it if others think the peek should stay.

**Comment by rharter** [comment]
LGTM 👍

**Pull request merged**
