### PR TITLE
Use getMethod() instead of getDeclaredMethod().

### PR DESCRIPTION
**Pull request by luciofm**
This add support for implementing a base interface or extending
a base abstract class while using @JsonQualifier annotations.

Closes https://github.com/rharter/auto-value-moshi/issues/32

### CODE REVIEW

**Comment by ZacSweers** [comment]
LGTM pending fixing the checkstyle issues

**Comment by luciofm** [comment]
@hzsweers most are simple line lenght that I'll fix, but this one:
`:auto-value-moshi:checkstyleTest[ant:checkstyle] [ERROR] /home/travis/build/rharter/auto-value-moshi/auto-value-moshi/src/test/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtensionTest.java:1: File length is 2,062 lines (max allowed is 2,000). [FileLength]`
can I increse the FileLength vaule?

**Comment by JakeWharton** [comment]
I'd just comment out the check.

**Comment by ZacSweers** [comment]
Thanks!

**Pull request merged**
