### PR TITLE
Fixes Java 7 compatibility

### PR DESCRIPTION
**Pull request by felipecsl**
Same as https://github.com/rharter/auto-value-parcel/issues/5

### CODE REVIEW

**Comment by felipecsl** [comment]
thanks :+1:

**Comment by luciofm** [comment]
@rharter can you push another SNAPSHOT, I think that this is my problem not being able to generate the Moshi code.

Using a hand compiled  jar is working fine
apt files('libs/auto-value-moshi-0.1-SNAPSHOT.jar')

**Comment by felipecsl** [comment]
yeah in fact im having the same problem. the snapshot was last updated on august 15, which is more than a month ago: https://oss.sonatype.org/content/repositories/snapshots/com/ryanharter/auto/value/auto-value-moshi/0.1-SNAPSHOT/

**Comment by rharter** [comment]
Just published a new snapshot.  I hope we get some movement on the Auto
repo soon so we can get off snapshots.

**Pull request merged**
