### PR TITLE
Fix generated adapter method for annotated method.

### PR DESCRIPTION
**Pull request by serj-lotutovici**
Previously the generated adapter method would look for an adapter based
on the methods `getReturnType()`, which would fail because the generic
type would be lost.

### CODE REVIEW

**Comment by rharter** [comment]
Thanks for the submission.  These tests were passing, so would you be able to update or create one that will fail without this?  That will protect from regressions.

**Comment by serj-lotutovici** [comment]
@rharter there was a test already `usesJsonQualifierAnnotations()` also updated.

**Comment by serj-lotutovici** [comment]
I can add an integration test which show cases the problem

**Comment by rharter** [comment]
I saw the test you updated, but that didn't demonstrate the failure, right?  (i.e. it passed)

**Comment by rharter** [comment]
If you just update that so it would fail in the case you're fixing, that should be fine.

**Comment by serj-lotutovici** [comment]
The only reliable way a see is to add a an integration test which show cases the problem. Something like:

```
@AutoValue
public abstract class MyObject {
  @CustomJson public abstract List<String> paths();
}
```

And the test would be as follows:

```
@Test public void shouldUseCustomJsonAdapter() throws Exception {
  JsonAdapter<MyObject> adapter = moshi.adapter(MyObject.class); // The generated code would fail here
  // some assertions here
}
```

**Comment by serj-lotutovici** [comment]
I can do that, but it will require some structural changes of the project... if that's ok with you?

**Comment by rharter** [comment]
Ahh, I see what you're saying.  That makes sense then.  This looks good to me.

Adding functional tests wouldn't hurt, but I won't make it a requirement for this.

**Comment by serj-lotutovici** [comment]
I'll follow up with a pr, with some functional tests

**Pull request merged**
