### PR TITLE
Move factory to separate artifact

### PR DESCRIPTION
**Pull request by ZacSweers**

### CODE REVIEW

**Comment by ZacSweers** [comment]
I have no idea what's up with these travis failures 🤔

**Review by rharter — APPROVED** [review]
Nice

**Comment by ZacSweers** [comment]
Travis CI seems hosed, just swapped it with github actions instead. Can revisit if you want in the future! Pretty happy with actions though :)

**Comment by rharter** [comment]
I really like Github Actions, and we use it internally, so that sounds great to me!

**Pull request merged**
